### ISSUE TITLE
https support?

### ISSUE THREAD

**Issue by blurmonk** [akrennmair/newsbeuter#136]
Hi

I have a self signed https site and trying to use NB with it. It looks like NB is not able to grab https content?

thanks

**Comment by Minoru** [comment]
@blurmonk, has your problem been resolved?

**Comment by gs93** [comment]
How about removing the `CURLOPT_SSL_VERIFYPEER` option from `src/utils.cpp` (line 846) and `rss/parser.cpp` (line 93)? I don't think it's a good idea to disable certificate validation by default because there might be tokens in the URL (e.g. your personal github feed contains one). BTW: I assume his problem was caused by the hostname verification (done by `CURLOPT_SSL_VERIFYHOST`) anyways.

**Comment by Minoru** [comment]
The case of credentials is a valid point. I split the discussion into #239; I'll look into it once 2.10 is released.
