### ISSUE TITLE
the 'doc' target confusion

### ISSUE THREAD

**Issue by jpnk** [akrennmair/newsbeuter#142]
- the readme doesn't mention the 'doc' target so when i run `make install` i get an error message saying that it can't find the docs it's supposed to install.
- also `asciidoc` isn't mentioned as a dependency.

**Comment by akrennmair** [comment]
Just because this repository is publicly accessible doesn't mean it is always (or ever) in a perfectly working state that is meant to be used by people that want to compile the latest version from git.

This is all undocumented on purpose because documentation is generated before each release, and the doc make target is removed from the Makefile.
