### ISSUE TITLE
Improve README readability

### ISSUE THREAD

**Issue by pickfire** [akrennmair/newsbeuter#185]
I think adding **.md** or **.rst** to README may let github display README better. (Just change the filename)

- Try adding **features** to *impress* the viewer.
- Try changing the **installation** to `make && make install` (one-liner)
- Try adding a **usage** section to show how to use configure and use it *easily*.
- Try adding a **contribute** section to show the *source code* and *issue tracker* or *whatever stuff that matters*.
- Try adding a **support** section showing the *mailing-lists*
- Try changing the **table** to https://github.com/i3/i3/blob/next/DEPENDS to get better view in terminal. **cons** - Bad view in README.???

Reference: http://docs.writethedocs.org/writing/beginners-guide-to-docs/#id1

**Comment by Minoru** [comment]
In #162, @simonnagl said:

> > Try adding a usage section to show how to use configure and use it easily.
>
> I think this whould be a good section. I will try to write it if @akrennmair want's that too.

I believe Newsbeuter does pretty good job explaining its usage upon first run.

> > Try adding a contribute section to show the source code and issue tracker or whatever stuff that matters.
>
> All this is on github. In my opinion this is not something which should be described at README.

READMEs weren't invented by or for GitHub; people who extract the file from a tarball they got from a friend should not be on a disadvantage.

> > Try adding a support section showing the mailing-lists
>
> Adding the mailinglist to README does not fit to me. In my opinion README should be kept as clean as possible and contain only information on how to build the software. All other information should be fond at man pages or homepage.

It's just a couple of lines, but I believe they slightly raise the probability of people asking questions, reporting bugs and such (instead of switching to the next thing). So no harm done.

As for point originally brought up by @pickfire:

> Try changing the table to https://github.com/i3/i3/blob/next/DEPENDS to get better view in terminal.

I don't see how that adds any value, so no, thanks.

**Comment by pickfire** [comment]
@Minoru, thanks. Now I notice that there is an irc channel for newsbeuter.
