### ISSUE TITLE
"Catchup All" is misleading

### ISSUE THREAD

**Issue by nielsk** [akrennmair/newsbeuter#216]
"Catchup All" is misleading. I wondered what the function does and thought it might add all items as a big list or whatever. I didn't expect that it "Marks all feeds as read". It should be renamed to exactly this.
Btw. it is missing in the documentation, too (at least I couldn't find it with my browser search).
Luckily I had a terminal window open for a "killall newsbeuter"
 In addition it would be nice to have an additional security question when one hits a "Mark All Read" (or "Catchup All")-button, if one really wants to mark all feeds as read. You might make it an option though.

**Comment by Minoru** [comment]
Moving this to 2.11 milestone. Can't even rename it for 2.10 because we don't have it translated and I have no time to wait for it to be translated.

**Comment by Minoru** [comment]
> It should be renamed to exactly this.

Done.

> Btw. it is missing in the documentation, too (at least I couldn't find it with my browser search).

Turns out the default key, `C`, was always there (see Table 2), but the docs never mentioned it at "catchup all". Kinda fixed now: the name that UI uses ("Mark All Read") is similar enough to the description that docs use ("Mark articles in all feeds read").

> In addition it would be nice to have an additional security question

This is a good idea. Split it into #476.

Thanks for reporting this, and sorry it took me so long to finally come around to realizing that you're right.
