### ISSUE TITLE
Delay when rebinding 'q' to Escape

### ISSUE THREAD

**Issue by deshtop** [akrennmair/newsbeuter#221]
Hello

I've noticed that when I

    bind-key ESC quit

in my config there is a significant delay upon hitting Escape (~ 1 second), this happens in all contexts.
Unbinding Escape first by

    unbind-key ESC

doesn't fix the issue.

I've tested ``Z`` and ``G`` instead of ``ESC`` which work fine.
Happens with ``newsbeuter 2.8``, debian jessie (stable) package (in ``urxvt`` as well as in ``xterm``).

**Comment by Minoru** [comment]
Sorry for belated reply - I missed the notification about new issue.

Escape key is [special in a way](http://unix.stackexchange.com/questions/23138/esc-key-causes-a-small-delay-in-terminal-due-to-its-alt-behavior/23149#23149); it can be used to emulate Alt key (`Esc s` is the same as `Alt+s`, for example). The delay is there so that you have time to actually press the second button. It's 1 second by default.

I've just pushed a fix that resets the default to 25ms (why so low? [Apparently, Vim uses the same](http://en.chys.info/2009/09/esdelay-ncurses/), and no one ever complained). One can still override it by setting `ESCDELAY` environment variable to whatever they want.
