### ISSUE TITLE
make install runs doc generation every time

### ISSUE THREAD

**Issue by carno** [akrennmair/newsbeuter#285]
After 0d117658371a23257210ea2e2c116121d7ae39e0 running `make install` or `make install-newsbeuter` triggers doc regeneration even when there were no changes.

BTW, it would be quite useful (at least from my perspective) for one to be able to compile & install newsbeuter without html documentation and having to install a couple of additional tools just to have those docs generated (after commit above I had to install asciidoc, libxml2-utils, docbook-xml & xlstproc packages on my debian system)

BTW2, adding these:
```
doc/newsbeuter-cfgcmds.txt
doc/newsbeuter-keycmds.txt
doc/newsbeuter.1
doc/podbeuter-cfgcmds.txt
doc/podbeuter.1
doc/xhtml/
```
to .gitignore would keep the `git status` cleaner after compilation

**Comment by Minoru** [comment]
> After 0d11765 running make install or make install-newsbeuter triggers doc regeneration even when there were no changes.

Fixed with 3912e9d. Thanks for reporting this!

> BTW, it would be quite useful (at least from my perspective) for one to be able to compile & install newsbeuter without html documentation and having to install a couple of additional tools just to have those docs generated (after commit above I had to install asciidoc, libxml2-utils, docbook-xml & xlstproc packages on my debian system)

But it's not just HTML docs that are being built, it's also the man pages. Don't you need them?

Anyway, I thought this over once more and realised that if I add `doc` dependency to `all` target, the default path (`make && sudo make install`) will still get the documentation, while other people can still install Newsbeuter without any docs (with `make newsbeuter && sudo make install-newsbeuter`, for example). So I rolled the change back with 35f7388.

And thanks once more for the PR fixing the `.gitignore` file!

**Comment by carno** [comment]
Thanks for the quick response :)

**Comment by Minoru** [comment]
We've just had a discussion on IRC with @tsipinakis, who drew my attention to the following fact: downstream users get tarballs with docs pre-built. Thus, I'm rolling things back: if someone needs documentation, they should explicitly build it via `make doc`.
