### ISSUE TITLE
Missing package json when compiling... but compiles anyway

### ISSUE THREAD

**Issue by giacecco** [akrennmair/newsbeuter#328]
Hi All,
I could install all dependencies described at https://github.com/akrennmair/newsbeuter#dependencies but for "json", on my Fedora 23. "json-c" is fine. The output I get is below, using both release 2.9 or the latest 34aaaaf25910024c0337cb6c3c3f6056595a71e3 (2.10?). Newsbeuter compiles and runs fine anyway.

```
[giacecco@giaceccos-linux newsbeuter-r2.9]$ sudo make
Makefile:20: config.mk: No such file or directory
Checking for package sqlite3... found
Checking for package libcurl... found
Checking for package libxml-2.0... found
Checking for package stfl... found
Checking for package json... not found
Checking for package json-c... found
Checking for package ncursesw5 using ncursesw5-config... found
msgfmt --statistics -o po/hu.mo po/hu.po
(...)
```

**Comment by Minoru** [comment]
That's an expected behaviour. As can be seen in [`config.sh:108`](https://github.com/akrennmair/newsbeuter/blob/master/config.sh#L108), checks for "json" and "json-c" are really a single check for two different names. I myself haven't seen platforms where json-c library is registered under the name "json", but I suppose there's a reason there's two checks instead of one. It surely didn't break anything yet :)
