### ISSUE TITLE
toggle-article-read (N) does not undelete an article marked for deletion (D)

### ISSUE THREAD

**Issue by giacecco** [akrennmair/newsbeuter#330]
Hi All, 
I'm using the current [head](https://github.com/akrennmair/newsbeuter/commit/34aaaaf25910024c0337cb6c3c3f6056595a71e3). The issue is all in the subject, it looks like a bug to me, but perhaps it's a feature?

Imagine you deleted an article and then changed your mind, and want to mark it as unread. With the current version of Newsbeuter what you do is:

    D (to delete it) - D (to undelete it) - N (to mark it as unread)

... but it feels more natural from a user point of view if it was sufficient to do:

    D (to delete it) - N (to undelete it and mark it as unread)

Note that the reverse is not true: an article can go from N to D without being read first.

What do you reckon?

**Comment by Minoru** [comment]
Yes, you're totally right, N should undelete and mark as read. Will fix in 2.11.

**Comment by giacecco** [comment]
Thanks, btw you talk about 2.11 but 2.10 is not officially released yet, at least [here](https://github.com/akrennmair/newsbeuter/releases), correct? I know the current head presents itself as 2.10 but I thought it was more of a RC.

**Comment by Minoru** [comment]
Yes, 2.10 isn't officially out yet because I don't have access to all the infrastructure, like newsbeuter.org. I've shot an email to @akrennmair but haven't heard back yet—maybe he's on vacation or something. I don't do tags and GitHub releases because I don't want to step on his toes. I'm using this pause as a break, too—no coding is being done, I only respond to issues and whatnot.

**Comment by giacecco** [comment]
I understand, is there some way to say thanks for your work btw?

**Comment by Minoru** [comment]
Words work just fine ;)
