### ISSUE TITLE
Itemlist_formaction testing only tests for two operations

### ISSUE THREAD

**Issue by tkerdonc** [akrennmair/newsbeuter#419]
**Newsbeuter version**: 2.10

The tests implemented in test/itemlist_formaction.cpp only test the two commands added in #380, but could be used to test all the other commands available in this formaction. This issue's main goal is to track the development currently ongoing in my [branch](https://github.com/tkerdonc/newsbeuter/tree/formaction_testing).

**Comment by tkerdonc** [comment]
Only three more commands implemented so far, thirty six remaining, would you rather have me submit a PR now for review purpose or wait a bit for it to be more consistent ?

**Comment by Minoru** [comment]
Technically this is about 2.10, because we didn't release those tests with 2.9. Happy to know you're working on this ^_^

A note regarding the structure of the tests: I found it to be easier when the tests are smaller, even if this means some things are duplicated from test to test. This way, you don't need to skim numerous screens of code to find pieces relevant to the small `REQUIRE` that's failing. In this particular case, I think writing separate `TEST_CASE` for each operation will be fine, and `SECTION`s can be used for different properties of each operation (don't forget about short, descriptive names for those ;)

**Comment by Minoru** [comment]
Re PR: submit it now. It's a big chunk of work, it will be a pain to review and update when it's completely done.

**Comment by tkerdonc** [comment]
Good point, fixing the version number. And you're right it will definitely need splitting into different TEST_CASEs while still grouping what is related (e.g open in brower commands with and without marking read.)
Now submitting a PR.

**Comment by Minoru** [comment]
With #420 merged and all its findings turned into separate issues, this one can be closed.
