### ISSUE TITLE
Bug or feature? Backtick expressions in config file are interpreted at startup

### ISSUE THREAD

**Issue by giacecco** [akrennmair/newsbeuter#435]
I am using newsbeuter 2.10 compiled from source (34aaaaf) on Linux. I need to define a macro that uses backticks, e.g.

```
macro L set browser "/usr/local/bin/t favorite `echo %u | sed -r 's/.*\/([0-9]+)$/\1/'` --profile=$HOME/.config/t/personal"; open-in-browser ; set browser "google-chrome"
```

... where ```%u``` is an URL to a tweet, e.g. _https://twitter.com/innovateuk/status/802107092161142784_. The backquoted expression returns the tweet id from the Twitter URL, in the example _802107092161142784_. ```t``` is [a command line Twitter client](https://github.com/sferik/t) that then favourites the tweet.

Unfortunately this macro definition does not work because newsbeuter interprets the backticks **at the moment it loads the configuration file** and not later, when the macro is called. Perhaps this is intended, but breaks my macro.

I have tried escaping the backtick but nothing I've tried working: \`, \\\`, ``. 

The issue may be considered close to https://github.com/akrennmair/newsbeuter/issues/335 .

**Comment by Minoru** [comment]
This is a de-facto feature because we've had it [for a while](https://github.com/akrennmair/newsbeuter/commit/8f6916c05bebf46b25fcf06d83e8fdfb75f1997a).

No relation to #335.

I think `bookmark-cmd` will be a better fit for your use-case. Have you considered it?

**Comment by giacecco** [comment]
Thanks @Minoru, clearly a feature (to someone) if it's documented. 

The issue / bug then becomes: how do I escape the backtick, so that it's executed when the macro is run, and not when the configuration file is read?

Thanks for the bookmarking suggestion, but that is not what I need. Many of the feeds I read are heavily-curated lists of tweets (see [here](https://github.com/Digital-Contraptions-Imaginarium/twitter2rss) if curious), so what I want to do is to actually trigger a "like" on twitter.

**Comment by Minoru** [comment]
> how do I escape the backtick, so that it's executed when the macro is run, and not when the configuration file is read?

I see three ways (two of which are more like dodging than really solving the problem):
1. just pack your whole command into a shell script and call *that* from the macro;
2. use `$()` instead of backticks;
3. upgrade to 1fa89012358 or newer, escape the backticks with backslashes, and pass your whole command to shell (`sh -c 'your command here'`). Additional escaping might be required to get all the quotes the way you want them.

> see here if curious

This actually looks interesting, but without an example of the output it's hard to understand how the resulting feed looks like. I gather that I'll get an Atom entry with a number of tweets in it, but then I don't understand how you're favouriting a particular tweet with `open-in-browser`.

**Comment by Minoru** [comment]
@giacecco, did any of the above suggestions help?

**Comment by giacecco** [comment]
Sorry I did not get back to you sooner @Minoru. I've solved the issue doing (1). 

About your other question, using "open-in-browser" to trick newsbeuter into launching shell scripts at runtime is described in newsbeuter's documentation [here](http://newsbeuter.org/doc/newsbeuter.html#_macro_support).
