### ISSUE TITLE
Feature Request: deleting a feed from within newsbeuter

### ISSUE THREAD

**Issue by heavyimage** [akrennmair/newsbeuter#484]
**Newsbeuter 2.9**:

I love newsbeuter so much -- thanks so much for creating it!

Just a probably silly feature request; Would it be possible to add a command to delete the selected feed from the urls file via Newsbeuter itself?  There are a lot of dead feeds in my list and crossreferencing between the newsbeuter ui and the urls file loaded in a text editor is slow going!

Jesse

**Comment by giacecco** [comment]
@heavyimage opening the ```urls``` file and deleting the feeds can't take that much effort or time. Are you sure you would divert the contributors' effort on that rather than on more useful improvements?

**Comment by Minoru** [comment]
@heavyimage Not silly at all! But I don't think implementing this within Newsbeuter makes much sense: editing a text file is a decent interface that's already familiar to any computer user; adding an alternative interface won't provide much benefit.

That said, the integration between Newsbeuter and the editor can be better. Luckily, we have an issue about precisely that: #258! Once resolved, it should make your task much easier to accomplish.

In the meantime, two things that can simplify your work are:

* disable feed sorting, then use feed numbers (the leftmost column by default) as line numbers (your editor is capable of jumping to a specified line, right?)
* enter the feed and look at the title—there's a URL there.

And regarding the *root cause* of all this, i..e. the dead feeds: I hope to find or think up a way of handling these somehow (logging them at least?), but this is still in "thinking" phase and I have bugs to fix before taking on new features.

**Comment by heavyimage** [comment]
Hey guys, thanks for this.  All sounds super reasonable.  I think this is sort of a special case in that for years of not using rss I'm trying to get back into it to manage all the things I care about / want to follow.  As such, after adding back tons and tons of feed urls (~500), a lot of them are totally busted and going back and forth is a bit tedious.

I suppose this is probably a one off problem so it may not warrant a first class feature, as such, but I agree with @Minoru that the integration between an editor and the application could be better (another benefit: adding / editing tags rather than going out to your editor).  #258 looks promising -- I'll follow that one now though unless it's going to be resolved immanently I'll probably end up just clearly out the dead links manually.

In regards to the last point, maybe a way of filtering to find feeds with no articles?

**Comment by Minoru** [comment]
> In regards to the last point, maybe a way of filtering to find feeds with no articles?

Let's move this discussion to #485.
