### ISSUE TITLE
Behavior when RSS enclosure and media:content is available

### ISSUE THREAD

**Issue by DerFlob** [akrennmair/newsbeuter#49]
Currently, when there is an enclosure element and/or one or more media:content elements in an RSS feed, the one last parsed gets set as enclosure_url.
Wouldn't it make sense, to prioritize the enclosure element, which was "designated" by the feed publisher, to be the primary media object associated with the feed's item.

The reason for me to propose this, is the blip.tv RSS feed. It has several versions of the videos, with different quality in a media:group and a playlist file as the last item in the media:group, which doesn't play, because is hasn't valid entries.
Prioritizing the enclosure element, would always give a valid video and IMHO be less "random" than just using the last element parsed.
Edit: a sample RSS feed: http://blip.tv/radio-dead-air/rss/

**Comment by Minoru** [comment]
Oh well… Blip.tv is gone, Maker.tv that's supposed to replace it doesn't even have RSS feeds, [Media RSS Specification (version 1.5.1 at the moment of writing)](http://www.rssboard.org/media-rss) doesn't specify if `media:content` have priority over `enclosure`s or not… So I won't do anything right away, because always choosing `enclosure` over `media:content` is just as arbitrary as status quo.

But I'm going to open an issue for a new feature, one that will enable users to choose from a list what they want to enqueue.

Thanks for the report, though, and sorry we got to it *so* damn late.
