### ISSUE TITLE
Query feeds doesn't reload

### ISSUE THREAD

**Issue by spiridoncha** [akrennmair/newsbeuter#512]
newsbeuter 2.10-abaa-dirty
System: Linux 3.16.0-4-amd64 (x86_64)
Compiler: g++ 4.9.2
ncurses: ncurses 5.9.20140913 (compiled with 5.9)
libcurl: libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3 (compiled with 7.38.0)
SQLite: 3.8.7.1 (compiled with 3.8.7.1)
libxml2: compiled with 2.9.1

Steps to reproduce the issue:
1. Empty config. 
2. Create "query feed". For example - "query:Unread Articles:unread = \"yes\""
3. Run newsbeuter. And even if I have some unread articles - my "query feed" will be empty.

I can reload all feeds and all will be fine. But if I try reload only my "query feed" - nothing happens and my "query feed" still empty.

**Comment by Minoru** [comment]
Thank you for the report!

> `"query:Unread Articles:unread = "yes""`

This is incorrect syntax, you probably meant `"query:Unread Articles:unread = \"yes\""`. I'm guessing you just typed this into the issue instead of copying, which is fine; but if you got your version in urls file and Newsbeuter didn't complain about it, please report it as a separate issue.

> Run newsbeuter. And even if I have some unread articles - my "query feed" will be empty.

You can set `prepopulate-query-feeds` to `yes` and it'll be updated on startup automatically. (I don't know why it's not set to "yes" by default—maybe it was considered to be a backwards-incompatible change.)

> But if I try reload only my "query feed" - nothing happens and my "query feed" still empty.

I can confirm that:

- the counts next to the feed aren't updated when the feed is updated with "r";
- the counts *are* updated when all feeds are updated with "R".

The query feed itself works fine for me though—I can enter it and all the articles show up there. Do you see the same thing, @spiridoncha?

This is also reproducible in 2.9.

**Comment by gs93** [comment]
Yeah, this is the intended behavior. I looked into this a few years ago (which is why `R` works, 11083e6) but you basically have to refresh every query feed on every refresh.

**Comment by spiridoncha** [comment]
@Minoru Yes, I see the same.
For my purpose, prepopulate-query-feeds is enough.
Thank you.
