### ISSUE TITLE
Quicker way to filter list

### ISSUE THREAD

**Issue by qoxxxx** [akrennmair/newsbeuter#517]
I'm quite new to Newsbeuter, so sorry if it's a dumb question ...
If I understand correctly, filtering feeds is done by searching (/) and filtering articles is done with **F**.
And using **F** means having to type `title =~ "something" or content =~ "something" `everytime.

It would be useful if there was a quicker way to grep the list, like
`Filter: something`    <- would mean `title =~ "something" or content =~ "something"`
or using **/** in the article view..  

newsbeuter 2.9 - http://www.newsbeuter.org/
Compilation date/time: Apr  3 2016 07:12:50
System: Linux 4.4.0-67-generic (x86_64)
Compiler: g++ 5.3.1 20160330
ncurses: ncurses 6.0.20160213 (compiled with 6.0)
libcurl: libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3 (compiled with 7.47.0)
SQLite: 3.11.0 (compiled with 3.11.0)
libxml2: compiled with 2.9.3

**Comment by Minoru** [comment]
> If I understand correctly, filtering feeds is done by searching (/) and filtering articles is done with F.

Both searching and filters can be used for feed- and articlelist. In addition, search can be used in article view. There's no requirement that says you should use search for feeds and filtering for articles.

> And using F means having to type title =~ "something" or content =~ "something"everytime.

1. If that's your use-case, search will suit it better because it does just this.
2. Filters don't necessarily include `title` and/or `content`; you can filter for unread articles, for example, which is impossible to do with search.

Does that clear things up for you?

Thanks for using Newsbeuter! ;)

**Comment by qoxxxx** [comment]
You're right, search (/) does also work for articlelist, and is what I want. But, in my experience, it doesn't when browsing articles from a query `"query:test:(tags # \"tag\" or tags # \"tag2\")"`, which I almost exclusively use. 
I thought articlelist and article-list-from-query was the same, but I guess, it's the same as if I filtered first and then tried to search something.

So I'm guessing it's not possible to search within filtered results or query.

Thank YOU for working on it, really ;)

**Comment by Minoru** [comment]
> But, in my experience, it doesn't when browsing articles from a query

Yes, this is a known bug (see #313). It's been fixed; the next release (2.10) will be able to search inside query feeds as well.

> So I'm guessing it's not possible to search within filtered results

Filtering and query feeds are a bit different, so even though search in query feeds is fixed, searching in filtered lists isn't. I'll file a separate issue about that, so we can close this one since your original question was answered.
