### ISSUE TITLE
`newsbeuter -x print-unread` doesn't print anything if it's already running

### ISSUE THREAD

**Issue by decibyte** [akrennmair/newsbeuter#608]
**Newsbeuter version (copy from `newsbeuter -v`)**:

newsbeuter 2.9 - http://www.newsbeuter.org/
System: Linux 4.13.0-39-generic (x86_64)
Compiler: g++ 7.1.0
ncurses: ncurses 6.0.20160625 (compiled with 6.0)
libcurl: libcurl/7.55.1 GnuTLS/3.5.8 zlib/1.2.11 libidn2/2.0.2 libpsl/0.18.0 (+libidn2/2.0.2) librtmp/2.3 (compiled with 7.55.0)
SQLite: 3.19.3 (compiled with 3.19.3)
libxml2: compiled with 2.9.4

Steps to reproduce the issue:

1. Start newsbeuter normally (i.e. with the interactive UI).

2. In another terminal, run `newsbeuter -x print-unread`. This prints nothings.

3. Quit the running newsbeuter in the first terminal, then try `-x print-unread` in the second terminal. This prints `236 unread articles`. 

**Other info you think is relevant**:

I have an instance of newsbeuter always running (inside a `tmux` session) on a remote server, connecting to this via SSH to read my news. I'd like to also have an indicator telling me how many unread items I have, for which I'd like to run the `-x print-unread` command in parallel with the already running instance. I suspect this is due to some sort of built in mechanism (a lock on the sqlite file or whatever), but can you explain why it doesn't work? And would it be possible to get this to work? For my indicator, I currently have another, home grown script to query the database, but I'd much rather use this built in feature of newsbeuter :)

**Comment by Minoru** [comment]
Newsbeuter is no longer maintained, please try my fork [Newsboat](https://github.com/newsboat/newsboat) instead. It's available in many Linux distros, a few BSDs, Homebrew, Snap store, and probably more.

As for your report: indeed, Newsbeuter locks the database, which prevents the second copy from obtaining the unread count. Newsboat does so, too. I advise you to update to Newsboat and stick with your script because:
1. Newsboat versions its DB schema, so you can make your script notify you if we deprecate something;
2. both Newsbeuter and Newsboat read pretty much the whole DB before processing your 'print-unread' command, which is slower than your custom SQL query. We're aware of the limitation and it chaffs us in other ways too, so it'll be removed eventually, but we've got some untangling to do first.

**Comment by decibyte** [comment]
Thx for pointing me in the right direction. I didn't know there's a new fork in town. I'll move to Newsboat.

I think my question has been answered. Thus, as such, I'm happy now. Let me know if you'd like me to create a similar issue for Newsboat.
